# Generated by Django 5.0.4 on 2024-04-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complted',
            new_name='completed',
        ),
    ]
